/* config.h. Generated by cmake from config.h.cmake */

#ifndef CONFIG_H
#define CONFIG_H

//////////////////////////////
// functions
//////////////////////////////
#cmakedefine HAVE_ISBLANK 1
#cmakedefine HAVE_MKSTEMP 1
#cmakedefine HAVE_SETENV 1
#cmakedefine HAVE_STRCASECMP 1
#cmakedefine HAVE_STRCASESTR 1
#cmakedefine HAVE_STRLWR 1
#cmakedefine HAVE_STRNCASECMP 1
#cmakedefine HAVE_LOCALTIME_R 1

//////////////////////////////
//support large files
//////////////////////////////
#if defined(_FILE_OFFSET_BITS) 
# if (_FILE_OFFSET_BITS<64)
#  undef _FILE_OFFSET_BITS
#  define _FILE_OFFSET_BITS 64
# endif
#else
# define _FILE_OFFSET_BITS 64
#endif

//////////////////////////////
//misc
//////////////////////////////
#cmakedefine ICONV_SECOND_ARGUMENT_IS_CONST 1

#define PATH_SEPARATOR ":"
#define LIBINSTALLDIR "${LIB_DESTINATION}"
#define SOURCEDIR "${CMAKE_CURRENT_SOURCE_DIR}"
#define BINARYDIR "${CMAKE_CURRENT_BINARY_DIR}"
#define INSTALLDIR "${CMAKE_INSTALL_PREFIX}"

#include <strigi/strigiconfig.h>

#endif //CONFIG_H
